### ISSUE TITLE
[RS] Move the request tracking from the building to citizen

### ISSUE THREAD

**Issue by marchermans** [ldtteam/minecolonies#1533]
In the current implementation the system stores requests on the building and processes them from their.
This had some advantages, in particular it allowed a simpler tracking of the requester (the building) inside of the request system.

This is ofcourse not the best solution and since I introduced an abstraction layer between the request system and the colony it is now possible to make the citizen the requester, with some small changes:

- [ ] Make the `IRequester` Interface return multiple possible delivery Locations.
- [ ] Change the abstraction layer to not track buildings but citizens
- [ ] Add methods to `CitizenData` to handle requests.

**Comment by Raycoms** [comment]
@OrionDevelopment is this still necessary?
