### ISSUE TITLE
1.13 task list of things that should be done before release

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2759]
Feel free to edit this... (priority from highest to lowest)

- [ ] Replace UIs with BlockOut
- [ ] Create a proper interaction with Structurize (including download manager @Nightenom)
- [x] fix for tileEntities: _Potentially Dangerous alternative prefix `minecraft` for name `minecolonies.colonybuilding`, expected `minecolonies`._
- [ ] split `WindowTownHall.java` per each switch (xml done)
- [ ] sort .lang files by alphabet and type (as it will get a port to json file), assign: @Nightenom (probably)
- [ ] fix comments to match theit classes etc.
- [ ] codacy and sonar cleanup

Edited:
Orion 8/7/2018
Nightenom 8/7/2018, 8/13, 8/27

**Comment by Nightenom** [comment]
Just please sort json files to remove duplicates. thanks
