### ISSUE TITLE
Mod Compatibility Requests:

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#4510]
This is a list of all requested mod compatibilities.
Please comment below if you want to request an additional compatibility that is not in the list.

- [ ] Herders accepting different animal mods: #4382, #3906, #2285
- [ ] Mouse tweaks compatibility with custom containers: #4356
- [ ] Special Tool compat: #4317, #1562
- [ ] Backpack integrations: #3550
- [ ] Farmer additional crops compat: #3549, #687 
- [ ] Cubic Chunks: #3486
- [ ] Chisel block support: #3191
- [ ] Lumberjack additional trees support: #3166, #3141
- [ ] Mo bends compat: #3272
- [ ] Bridge pathing compat: #3165
- [ ] Custom armour support: #3154 
- [ ] Builder special placement support: #3094, #3095
- [ ] Fisherman rods support: #3083, #2537
- [ ] Special Mod Dimension support: #3063
- [ ] Special weather mod support: #2743
- [ ] Overlay mod support: #2728
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by ravenbuilder934** [comment]
Can we change it so Quark and other inventory sorting mods can sort the hut and warehouse inventories?

**Comment by Profilename1** [comment]
Better support for modded ores. It appears that the list for the miner's lucky blocks doesn't accept blocks that use sub ids. That is, minecraft:diamond_ore is fine while immersiveengineering:ore:3 doesn't seem to work at all.

**Comment by hron84** [comment]
@Profilename1 is this for 1.12? As far as I know, 1.14+ moved away from sub ids, they use flat block/item names instead.

**Comment by Profilename1** [comment]
@hron84 yes. I've found a workaround for my specific application but figured I would mention it here anyway.

**Comment by KumulaKai** [comment]
At least in the 1.14.4 version the villagers can't path across bridges from Macaw's Bridges. You can place waypoints over every bridge and then ends of the whole bridge but they will only sometimes slowly hop over them. Tried adding blocks under the bridge and way point under the bridge and a few variations of the two. But they will only cross if there is a waypoint on every bridge block. It'd be awesome if they would path find over those. Let me know if any more info is needed.

**Comment by McKitten** [comment]
Serene Seasons compatibility.
Fields require glowstone under the water to prevent it icing over and drying the farmland out. Sugarcane plantations can get away with extra lighting in the center but not sure about the others.
