### ISSUE TITLE
Bunch of issues I've met during playing

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#6657]
List of random nitpicks/issues to fix:
_If you are not from dev team and want to comment please create a new issue and describe it properly_

- [x] 1) negative and weird percentage during requirements gathering phase, #6726
![image](https://user-images.githubusercontent.com/17338378/109997828-e6cbd980-7d10-11eb-8aa0-acf7fdaa4d84.png)
- [x] 2) ~lumberjack spinning when idling (when having no work)~ overridden by 9, #6678
- [x] 3) lumberjack restriction area has either bad chat info or does not work properly - not sure if it's 3d or 2d, if 3d then bad chat info, if 2d then he does not detect trees correctly - should be probably 2d from level y, #6678
- [x] 4) chest are still considered as storage but citizens do not consider them when searching items
- [x] 5) lumberjack should have separate toggles for planting and chopping - requires small gui redesign (box should have two lines probably: itemicon (left-aligned), first line sapling name, second line two toggles - chop and plant
- [x] 6) citizen should have stronger ai task for doors of citizen huts (houses), the current one is lenient cause of chunk-loading, special handling or stronger task should be used so doors are always closed during night
#### edit 1:
- [x] 7) remove alpha from tool textures, #6726
![image](https://user-images.githubusercontent.com/17338378/110027671-91a0bf80-7d32-11eb-9997-28c441afa54f.png)
- [ ] 8) minecolonies build tool requires having hut block to display its schematic, this is rather problematic when using preview sharing since other players are required to have the block too otherwise their build tool resets the schematic to decos (to raven - I consider this to be a bug)
#### edit2:
- [x] 9) (overrides 2) lumberjack looping in no_tree_found and start_working stages when no tree found, #6678
a) searchIncrement is never resetted
b) [this code](https://github.com/ldtteam/minecolonies/blob/version/1.16.3/src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java#L335) is problematic in setTree because the setTree doesn't take restriction in account thus lumber just spins between restriction area and building
c) waitBeforeCheckingAgain is not working as intended, the AI never pauses if no_tree_found state is hit
- [x] 10) [code](https://github.com/ldtteam/minecolonies/pull/6659/files#diff-9623ce8a29e14a2b175b5be13523cb1a6fb53ece1efb1d92d0ec976d83557841L515-L521) add new ctor to our container and remove packet buffer, #6676
#### edit3:
- [x] 11) block placing still not working correctly in terms of block update, #6677
- [x] 12) waypoints not rendering, blame me - it's working
- [x] 13) add partial tick to colony border rendering, #6675

**Comment by ravenbuilder934** [comment]
5 is a feature request, not a bug - doesn't go here

**Comment by Raycoms** [comment]
Lumberjack restriction area is 3d.

**Comment by Raycoms** [comment]
I don't see a huge need for 6. 5 is definitely a feature request.

**Comment by Raycoms** [comment]
@ravenbuilder934 can probably adjust the chat for 3

**Comment by Nightenom** [comment]
![image](https://user-images.githubusercontent.com/17338378/110000286-68bd0200-7d13-11eb-88ab-d5271c3406e5.png)
should be probably better phrased then, also if it's 3d then max y doesn't apply - probably intended but should be noted then
