### ISSUE TITLE
Crash with Epic Fight

### ISSUE THREAD

**Issue by Yesssssman** [ldtteam/minecolonies#8357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.673-ALPHA

### Structurize Version

structurize-1.18.2-1.0.389-RELEASE

### Related Mods and their Versions

Forge 40.1.0

### Reproduction Steps

Hello, I'm a creator of Epic Fight and I've got a crash report that conflicts with MineColonies. the direct reason for the crash is this:

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.GameRules.getBoolean(net.minecraft.world.level.GameRules$Key)" because the return value of "net.minecraft.world.level.Level.getGameRules()" is null
```

So, I wonder if MineColonies creates a level instance that returns a null value for getGameRules() method. If there's a reason it should be a null value, I'll just check if it is null before executing my code. Thanks.

The original page for this report is here: https://github.com/Yesssssman/epicfightmod/issues/990

### Logs

https://gist.github.com/Yesssssman/b384facc0a6041618bb66b3f293839ad

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
