### ISSUE TITLE
AI tracking ( Block Pos error with my NPC AI)

### ISSUE THREAD

**Issue by UrPrice** [ldtteam/minecolonies#8449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.775-ALPHA

### Structurize Version

1.18.2-1.0.399-RELEASE

### Related Mods and their Versions

Forge 40.1.25
BlockUI - idk (not found in mod lib, maybe have not)
Domum Orm. - 1.18.2 - 1.0.50-ALPHA

### Reproduction Steps

Idk, i just meet my NPC with msg about bug, then check server console log and copy existing error:

```
[20:58:59] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@1c12ed42 threw an exception:
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?] {}
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?] {}
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onUpgradeComplete(AbstractBuilding.java:958) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.buildings.AbstractSchematicProvider.upgradeBuildingLevelToSchematicData(AbstractSchematicProvider.java:549) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.buildings.AbstractSchematicProvider.onUpgradeSchematicTo(AbstractSchematicProvider.java:557) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.api.tileentities.AbstractTileEntityColonyBuilding.readSchematicDataFromNBT(AbstractTileEntityColonyBuilding.java:234) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.jobs.AbstractJobStructure.complete(AbstractJobStructure.java:145) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructureWithWorkOrder.executeSpecificCompleteActions(AbstractEntityAIStructureWithWorkOrder.java:366) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.completeBuild(AbstractEntityAIStructure.java:266) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.m_8037_(AbstractAISkeleton.java:133) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading}
	at com.minecolonies.api.entity.CustomGoalSelector.m_25373_(CustomGoalSelector.java:231) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:698) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2506) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading,re:mixin}
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:401) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:685) ~[minecolonies-1.18.2-1.0.775-ALPHA.jar%2368!/:1.18.2-1.0.775-ALPHA] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:vampirism.mixins.json:LivingEntityAccessor,pl:mixin:APP:vampirism.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:486) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%2394!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
> 
[20:58:59] [Server thread/ERROR] [minecolonies/]: Pausing Entity Norah M. Clifford (com.minecolonies.job.builder) at BlockPos{x=-870, y=94, z=2728} for 100 Seconds because of error:
> java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.colony.buildings.AbstractBuilding.onUpgradeComplete(AbstractBuilding.java:958)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.colony.buildings.AbstractSchematicProvider.upgradeBuildingLevelToSchematicData(AbstractSchematicProvider.java:549)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.colony.buildings.AbstractSchematicProvider.onUpgradeSchematicTo(AbstractSchematicProvider.java:557)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.tileentities.AbstractTileEntityColonyBuilding.readSchematicDataFromNBT(AbstractTileEntityColonyBuilding.java:234)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.colony.jobs.AbstractJobStructure.complete(AbstractJobStructure.java:145)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructureWithWorkOrder.executeSpecificCompleteActions(AbstractEntityAIStructureWithWorkOrder.java:366)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.completeBuild(AbstractEntityAIStructure.java:266)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.m_8037_(AbstractAISkeleton.java:133)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.CustomGoalSelector.m_25373_(CustomGoalSelector.java:231)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Mob.m_6140_(Mob.java:698)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2506)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Mob.m_8107_(Mob.java:495)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:401)
	at TRANSFORMER/minecolonies@1.18.2-1.0.775-ALPHA/com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:685)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.Mob.m_8119_(Mob.java:307)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.Level.m_46653_(Level.java:486)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Logs

https://pastebin.com/3VDPru6j

### Anything else?

I did, because u ask. I don't need answer for this debug report, thanks o/ 

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This has been fixed already
