### ISSUE TITLE
[BUG] Courier Hut Task List 

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#8947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1248-ALPHA

### Structurize Version

structurize-1.19.2-1.0.480-ALPHA

### Current Behavior

The current courier hut task list cuts off a lot of information and is hard to read.
![image](https://user-images.githubusercontent.com/34487065/218879397-3c73a0d4-b672-4221-8e40-4124e246db8c.png)

Here, there's no information about what is being delivered at all.
![image](https://user-images.githubusercontent.com/34487065/218879506-65f9248b-9118-440f-91d3-b84197b33287.png)

It's not clear what delivering to the "Request System" means.
![image](https://user-images.githubusercontent.com/34487065/218879830-d689ea78-5a5d-432f-96e6-732b0d327ea2.png)

### Expected Behavior

A more informative task list that doesn't cut off as much text, e.g.:

- Not cutting off names of items
- Not cutting off names of workers
- Rather than an arrow denoting transport, "From: Warehouse \n To: Builder's Hut: Amina A. Crosby"
- Numbered tasks
- Other UI improvements? 

### Reproduction Steps

1. Have a warehouse and some courier huts/couriers.
2. Have other buildings request items.
3. Look at the courier hut task list.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
