### ISSUE TITLE
[BUG] Crash when Clicking "Task List" in Restaurant

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#9093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1378-ALPHA

### Structurize Version

structurize-1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

domum_ornamentum-1.19-1.0.83-ALPHA-universal

### Current Behavior

Clicking the task list button on the restaurant GUI causes the game to stop responding, forcing a crash to close it.

![image](https://user-images.githubusercontent.com/34487065/233855991-3a856f98-218d-4776-acd7-6c3d8afd729a.png)

### Expected Behavior

I should be able to see the tasks of the restaurant.

### Reproduction Steps

Not sure, but:
Start colony, build level 3 restaurant in fortress style?
Hire cook and assistant cook.
Set a min stock in the restaurant for a bunch of cooked meats.
Click task list.

### Logs

https://gist.github.com/anonymous563/a86c3b73f8e700b2d23af4fd9d3fc553

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by anonymous563** [comment]
Not sure what I did, but it doesn't crash anymore. If you see something I did in the crash log, please let me know.

**Comment by MotionlessTrain** [comment]
I couldn't see a crash in the log

**Comment by Raycoms** [comment]
Please reopen when able to reproduce with crash log in report then

**Comment by anonymous563** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/11638703/latest.log)

It says the colony  has a very big memory imprint? Again, happened when opening the restaurant task list. Minecraft stopped responding when I clicked it.

This crash happened again after closing Minecraft and reopening. I've waited several minutes, but it's still not responding.

**Comment by anonymous563** [comment]
@Raycoms please reopen!

Reproduction steps:
Load into single player world in my colony.
Click restaurant task list.
Watch "Not Responding" occur.

Could it be an issue with colony size?

**Comment by Raycoms** [comment]
Ill reopen if you give me a crash log =P

**Comment by anonymous563** [comment]
https://github.com/ldtteam/minecolonies/issues/9093#issuecomment-1574290774
This is the crash log, no?

**Comment by Raycoms** [comment]
No, just latest log without any crash report in it

**Comment by anonymous563** [comment]
It goes into "Not Responding" mode and nothing happens until I alt+F4 it (for at least 15 min). 
What should I do instead?
